<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<!--<TargetFrameworks>net481;net8.0-windows;net9.0-windows;net10.0-windows</TargetFrameworks>-->
		<TargetFrameworks>net481;net8.0-windows;net9.0-windows</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>disable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Demos</RootNamespace>
		<OutputPath>..\..\bin\</OutputPath>
		<IncludeSymbols>False</IncludeSymbols>
		<NeutralResourcesLanguage>en-US</NeutralResourcesLanguage>
		<ApplicationHighDpiMode>DpiUnaware</ApplicationHighDpiMode>
		<SatelliteResourceLanguages>ko-KR;zh-CN;ja-JP;de-DE</SatelliteResourceLanguages>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework.StartsWith(`net9.0-windows`))' OR '$(TargetFramework.StartsWith(`net10.0-windows`))'">
		<WarningsNotAsErrors>$(WarningsNotAsErrors);WFO1000</WarningsNotAsErrors>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net481'">
		<DefineConstants>$(DefineConstants);OPENTK3</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework.StartsWith(`net8.0-windows`))' OR '$(TargetFramework.StartsWith(`net9.0-windows`))' OR '$(TargetFramework.StartsWith(`net10.0-windows`))'">
		<DefineConstants>$(DefineConstants);OPENTK4</DefineConstants>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)'=='net481'">
		<PackageReference Include="OpenTK" Version="3.3.3" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework.StartsWith(`net8.0-windows`))' OR '$(TargetFramework.StartsWith(`net9.0-windows`))' OR '$(TargetFramework.StartsWith(`net10.0-windows`))'">
		<PackageReference Include="OpenTK" Version="4.9.4" />
		<PackageReference Include="OpenTK.Mathematics" Version="4.9.4" />
	</ItemGroup>

	<ItemGroup>
	  <AdditionalFiles Remove="app.manifest" />
	</ItemGroup>
	
	<ItemGroup>
	  <Compile Include="..\helper.cs" Link="helper.cs" />
	  <Compile Include="..\nativemethods.cs" Link="nativemethods.cs" />
	</ItemGroup>
	
	<ItemGroup>
	  <None Include="..\config_syncaxis.ini" Link="config_syncaxis.ini">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>


	<!-- To copy(or overwrite) specific RTC6 files for syncAXIS v1.8.2 -->
	<!--
	<Target Name="OverrideRTCFilesForSyncAXIS" AfterTargets="Build">
		<Copy
			SourceFiles="$(TargetDir)syncaxis\bin64\RTC6DLLx64.dll"
			DestinationFolder="$(TargetDir)x64\"
			OverwriteReadOnlyFiles="true" />
		<Copy
			SourceFiles="$(TargetDir)syncaxis\bin\RTC6DLL.dll"
			DestinationFolder="$(TargetDir)x32\"
			OverwriteReadOnlyFiles="true" />
		<Copy
			SourceFiles="$(TargetDir)syncaxis\ProgramFiles\RTC6Dat.dat"
			DestinationFolder="$(TargetDir)"
			OverwriteReadOnlyFiles="true" />
		<Copy
			SourceFiles="$(TargetDir)syncaxis\ProgramFiles\RTC6Eth.out"
			DestinationFolder="$(TargetDir)"
			OverwriteReadOnlyFiles="true" />
		<Copy
			SourceFiles="$(TargetDir)syncaxis\ProgramFiles\RTC6Out.out"
			DestinationFolder="$(TargetDir)"
			OverwriteReadOnlyFiles="true" />
		<Copy
			SourceFiles="$(TargetDir)syncaxis\ProgramFiles\RTC6RBF.rbf"
			DestinationFolder="$(TargetDir)"
			OverwriteReadOnlyFiles="true" />
	</Target>
	-->

	<ItemGroup>
		<PackageReference Include="SpiralLab.Sirius3.Dependencies" Version="1.*" />
		<PackageReference Include="SpiralLab.Sirius3" Version="1.*" />
		<PackageReference Include="SpiralLab.Sirius3.UI" Version="1.*" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

</Project>
